# Generated by Django 5.0.2 on 2024-07-13 19:12

import buja_spot.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('event_time_start', models.DateTimeField()),
                ('event_time_end', models.DateTimeField()),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='event_images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('organizer_name', models.CharField(max_length=255)),
                ('organizer_phone', models.CharField(max_length=8)),
                ('organizer_address', models.CharField(max_length=255)),
                ('location_name', models.CharField(max_length=255)),
                ('complete_address', models.TextField()),
                ('location_lat', models.FloatField()),
                ('location_lon', models.FloatField()),
                ('is_active', models.BooleanField(default=False)),
                ('tags', models.CharField(default='default_tag', max_length=255, validators=[buja_spot.models.validate_tags])),
                ('user', models.ForeignKey(default='general', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buja_spot.eventcategory')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buja_spot.eventtype')),
            ],
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buja_spot.eventtype'),
        ),
        migrations.CreateModel(
            name='EventTicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buja_spot.event')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buja_spot.tickettype')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_types',
            field=models.ManyToManyField(through='buja_spot.EventTicketType', to='buja_spot.tickettype'),
        ),
    ]
