# Generated by Django 5.0.2 on 2024-07-13 19:51

import buja_spot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buja_spot', '0002_alter_event_tags_alter_event_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[buja_spot.models.validate_tags]),
        ),
    ]
